# Generated by Django 2.2.20 on 2021-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_remove_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.CharField(default='清华出版社', max_length=20, verbose_name='图书出版社'),
        ),
    ]
